# Generated by Django 4.2.5 on 2023-10-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_contactmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactmodel',
            new_name='Contact',
        ),
    ]
